homeassistant:
  name: Battery Level Card Dev

lovelace:
  mode: yaml
  resources:
    - url: /local/community/battery-level-card/battery-level-card.js
      type: module

input_number:
  test_battery:
    name: Test Battery
    min: 0
    max: 100
    step: 1
    initial: 75
    unit_of_measurement: "%"
    icon: mdi:battery

template:
  - sensor:
      - name: Test Battery Level
        state: "{{ states('input_number.test_battery') | int }}"
        unit_of_measurement: "%"
        device_class: battery
